import test from'node:test';import assert from'node:assert/strict';
import{createCatalog}from'../src/catalog/catalog-adapter.mjs';
import{stabilizeSelection,getAllowedValues}from'../src/catalog/catalog-resolver.mjs';
import{LIXIL_REFORM_SHUTTER_MODULE}from'../src/catalog/modules/lixil-reform-shutter-v1.mjs';
import{PRODUCT_NODES,INSTALLATION_CONFIGS,INSTALLATION as I,OPERATION as O,SHUTTER as S,VENTILATION as VF,POWER as PW}from'../src/catalog/modules/lixil-reform-shutter-master.mjs';
const c=createCatalog([LIXIL_REFORM_SHUTTER_MODULE]),p=LIXIL_REFORM_SHUTTER_MODULE.product.id;
const vals=(k,s)=>getAllowedValues(c,p,k,s).map(x=>x.value);
const resolve=(input)=>stabilizeSelection(c,p,input);
const base=(extra={})=>({
 opening_usage:'WINDOW',existing_window_type:'SLIDING_WINDOW',building_structure:'WOOD_CONVENTIONAL',exterior_wall_type:'FIBER_CEMENT_SIDING',installation_config:I.STANDARD,
 existing_sash_outer_width_ws:1504,existing_sash_outer_height_hs:2050,existing_sash_projection_mm:20,substrate_member:'NONE',available_top_space_c:250,available_bottom_space_d:65,available_side_space_left:60,available_side_space_right:60,
 exterior_wall_thickness_mm:30,post_width_mm:90,screw_engagement_mm:30,screw_torque_nm:1,leak_trace_present:'NO',mounting_surface_same_plane:'YES',obstacle_present:'NO',installation_scaffold_available:'YES',maintenance_access_available:'YES',soffit_mounting:'NO',
 operation_type:O.ELECTRIC,shutter_type:S.STANDARD,ventilation_function_type:VF.NONE,exterior_color:'T',power_supply_type:PW.AC100,wiring_route:'INDOOR',smart_control_app:'NONE',box_type:'S',typhoon_stopper:'NO',regulatory_confirmation_required:'NO',...extra
});
const vent=(extra={})=>base({shutter_type:S.VENTILATION,ventilation_function_type:VF.FLAP,primary_remote_type:'SINGLE_FUNCTION',...extra});
const wind=(extra={})=>base({shutter_type:S.WIND,ventilation_function_type:VF.NONE,security_building_component:'NO',...extra});
const manualStd=(extra={})=>base({operation_type:O.MANUAL,shutter_type:S.STANDARD,ventilation_function_type:VF.NONE,manual_external_key:'NO',...extra});
const manualWind=(extra={})=>base({operation_type:O.MANUAL,shutter_type:S.WIND,ventilation_function_type:VF.NONE,security_building_component:'NO',...extra});
const valid=(r,msg='')=>assert.equal(r.finalConfigurationStatus,'ORDERABLE',msg||JSON.stringify({v:r.validation,m:r.manualWarnings,s:r.selection,r:r.resolvedFields}));
const invalid=(r,code)=>{assert.equal(r.finalConfigurationStatus,'INVALID_CONFIGURATION');assert.ok(r.validation.errors.some(x=>x.errorCode===code),JSON.stringify(r.validation));};

test('formal master architecture is frozen at 5 product nodes / 9 installation configs',()=>{assert.equal(PRODUCT_NODES.length,5);assert.equal(INSTALLATION_CONFIGS.length,9);assert.equal(LIXIL_REFORM_SHUTTER_MODULE.product.formalStatus,'FORMAL_PASS');assert.equal(LIXIL_REFORM_SHUTTER_MODULE.product.runtimeReady,true);});
test('standard electric derives CW/CH and is orderable',()=>{const r=resolve(base());valid(r);assert.equal(r.selection.shutter_width_cw,1500);assert.equal(r.selection.shutter_height_ch,2000);assert.equal(r.resolvedFields.product_node_id,'PN-LIX-RSH-E-STD');assert.equal(r.resolvedFields.final_availability,'AVAILABLE');});
test('manual hides ventilation and three-side hides ventilation',()=>{let r=resolve(base({operation_type:O.MANUAL}));assert.equal(vals('shutter_type',r.selection).includes(S.VENTILATION),false);r=resolve(base({installation_config:I.THREE_SIDE,existing_sash_outer_height_hs:1995,available_top_space_c:250,available_side_space_left:60,available_side_space_right:60,floor_to_exterior_finish_bottom_mm:100}));assert.equal(vals('shutter_type',r.selection).includes(S.VENTILATION),false);});
test('ventilation hides AC adapter and bronze',()=>{const r=resolve(vent());assert.equal(vals('power_supply_type',r.selection).includes(PW.ADAPTER),false);assert.equal(vals('exterior_color',r.selection).includes('B'),false);});
test('wind exposes fixed ventilation but security is hidden when fixed ventilation is selected',()=>{let r=resolve(wind());assert.ok(vals('ventilation_function_type',r.selection).includes(VF.FIXED));r=resolve(wind({ventilation_function_type:VF.FIXED}));assert.equal(vals('security_building_component',r.selection).includes('YES'),false);});
test('one-side corner hides security YES and evaluates opposite E side',()=>{let r=resolve(wind({installation_config:I.CORNER,corner_side:'LEFT',existing_sash_outer_width_ws:1560,available_top_space_c:250,available_bottom_space_d:65,available_side_space_left:0,available_side_space_right:60}));assert.equal(vals('security_building_component',r.selection).includes('YES'),false);valid(r);r=resolve(wind({installation_config:I.CORNER,corner_side:'LEFT',existing_sash_outer_width_ws:1560,available_top_space_c:250,available_bottom_space_d:65,available_side_space_left:0,available_side_space_right:59}));invalid(r,'INSTALL_SPACE_INVALID');});
test('soffit permits D only and requires inspection access',()=>{let r=resolve(base({soffit_mounting:'YES',soffit_inspection_access:'YES',box_type:'D'}));assert.deepEqual(vals('box_type',r.selection),['D']);valid(r);r=resolve(base({soffit_mounting:'YES',soffit_inspection_access:'NO',box_type:'D'}));invalid(r,'SOFFIT_INSPECTION_INVALID');});
test('RC uses max of RC-opening and sash-derived CW/CH',()=>{const r=resolve(base({building_structure:'RC',exterior_wall_type:'RC',installation_config:I.RC,rc_surface_finish:'EXPOSED_CONCRETE',existing_sash_outer_width_ws:1500,existing_sash_outer_height_hs:2050,rc_opening_width_mm:1490,rc_opening_height_mm:2070,available_top_space_c:265,available_bottom_space_d:90,available_side_space_left:70,available_side_space_right:70}));valid(r);assert.equal(r.selection.cw_rc_candidate,1512);assert.equal(r.selection.cw_sash_candidate,1500);assert.equal(r.selection.shutter_width_cw,1512);assert.equal(r.selection.ch_rc_candidate,2055);assert.equal(r.selection.ch_sash_candidate,2000);assert.equal(r.selection.shutter_height_ch,2055);});

test('36-case Golden/Boundary matrix passes expected runtime outcomes',()=>{
 const cases=[
  ['GT01 E-STD',base(),'ORDERABLE'],['GT02 E-VENT',vent(),'ORDERABLE'],['GT03 E-WIND',wind(),'ORDERABLE'],['GT04 M-STD',manualStd(),'ORDERABLE'],['GT05 M-WIND',manualWind(),'ORDERABLE'],
  ['GT06 E-STD CW min',base({existing_sash_outer_width_ws:1159,existing_sash_outer_height_hs:580}),'ORDERABLE'],['GT07 E-STD CW min-1',base({existing_sash_outer_width_ws:1158}),'INVALID_CONFIGURATION','SIZE_OUT_OF_RANGE'],['GT08 E-STD CW max',base({existing_sash_outer_width_ws:2908}),'ORDERABLE'],['GT09 E-STD CW max+1',base({existing_sash_outer_width_ws:2909}),'INVALID_CONFIGURATION','SIZE_OUT_OF_RANGE'],
  ['GT10 E-STD CH min',base({existing_sash_outer_height_hs:580}),'ORDERABLE'],['GT11 E-STD CH min-1',base({existing_sash_outer_height_hs:579}),'INVALID_CONFIGURATION','SIZE_OUT_OF_RANGE'],['GT12 E-STD CH max',base({existing_sash_outer_height_hs:2512}),'ORDERABLE'],['GT13 E-STD CH max+1',base({existing_sash_outer_height_hs:2513}),'INVALID_CONFIGURATION','SIZE_OUT_OF_RANGE'],
  ['GT14 C 249',base({available_top_space_c:249}),'INVALID_CONFIGURATION','INSTALL_SPACE_INVALID'],['GT15 C 250',base({available_top_space_c:250}),'ORDERABLE'],['GT16 D 64',base({available_bottom_space_d:64}),'INVALID_CONFIGURATION','INSTALL_SPACE_INVALID'],['GT17 D 65',base({available_bottom_space_d:65}),'ORDERABLE'],['GT18 E 59',base({available_side_space_left:59}),'INVALID_CONFIGURATION','INSTALL_SPACE_INVALID'],['GT19 E 60',base({available_side_space_left:60}),'ORDERABLE'],
  ['GT20 post89',base({post_width_mm:89}),'INVALID_CONFIGURATION','POST_WIDTH_INVALID'],['GT21 post90',base({post_width_mm:90}),'ORDERABLE'],['GT22 screw29',base({screw_engagement_mm:29}),'INVALID_CONFIGURATION','SCREW_ENGAGEMENT_INVALID'],['GT23 screw30',base({screw_engagement_mm:30}),'ORDERABLE'],['GT24 torque0.9',base({screw_torque_nm:.9}),'INVALID_CONFIGURATION','SCREW_TORQUE_INVALID'],['GT25 torque1.0',base({screw_torque_nm:1}),'ORDERABLE'],
  ['GT26 projection99',base({existing_sash_projection_mm:99,substrate_member:'LARGE'}),'ORDERABLE'],['GT27 projection100',base({existing_sash_projection_mm:100,substrate_member:'LARGE'}),'INVALID_CONFIGURATION','SASH_PROJECTION_INVALID'],['GT28 wall45',base({exterior_wall_thickness_mm:45}),'MANUAL_CONFIRMATION_REQUIRED'],['GT29 wall45.1',base({exterior_wall_thickness_mm:45.1}),'INVALID_CONFIGURATION','WALL_THICKNESS_INVALID'],
  ['GT30 FRP150',base({installation_config:I.BALCONY,balcony_frp_difference_mm:150,sash_bottom_to_exterior_finish_bottom_mm:160,hs_lower_edge_to_floor_mm:100,available_top_space_c:250,available_bottom_space_d:100}),'ORDERABLE'],['GT31 FRP151',base({installation_config:I.BALCONY,balcony_frp_difference_mm:151,sash_bottom_to_exterior_finish_bottom_mm:160,hs_lower_edge_to_floor_mm:100,available_top_space_c:250,available_bottom_space_d:100}),'INVALID_CONFIGURATION','BALCONY_FRP_INVALID'],
  ['GT32 three-side500',manualStd({installation_config:I.THREE_SIDE,existing_sash_outer_width_ws:1504,existing_sash_outer_height_hs:1995,available_top_space_c:250,available_side_space_left:60,available_side_space_right:60,floor_to_exterior_finish_bottom_mm:500}),'ORDERABLE'],['GT33 three-side501',manualStd({installation_config:I.THREE_SIDE,existing_sash_outer_width_ws:1504,existing_sash_outer_height_hs:1995,available_top_space_c:250,available_side_space_left:60,available_side_space_right:60,floor_to_exterior_finish_bottom_mm:501}),'INVALID_CONFIGURATION','THREE_SIDE_HEIGHT_INVALID'],
  ['GT34 special window',base({existing_window_type:'SPECIAL_WINDOW'}),'MANUAL_CONFIRMATION_REQUIRED'],['GT35 removable obstacle',base({obstacle_present:'YES',obstacle_removable:'YES'}),'MANUAL_CONFIRMATION_REQUIRED'],['GT36 regulatory',base({regulatory_confirmation_required:'YES'}),'MANUAL_CONFIRMATION_REQUIRED']
 ];
 assert.equal(cases.length,36);
 for(const[name,input,status,code]of cases){const r=resolve(input);assert.equal(r.finalConfigurationStatus,status,`${name}: ${JSON.stringify({v:r.validation,m:r.manualWarnings,s:r.selection,r:r.resolvedFields})}`);if(code)assert.ok(r.validation.errors.some(x=>x.errorCode===code),name);}
});

test('metal siding and outdoor wiring require a substrate member',()=>{let r=resolve(base({exterior_wall_type:'METAL_SIDING',substrate_member:'NONE'}));invalid(r,'SUBSTRATE_REQUIRED');r=resolve(base({wiring_route:'OUTDOOR',substrate_member:'NONE'}));invalid(r,'SUBSTRATE_REQUIRED');r=resolve(base({exterior_wall_type:'METAL_SIDING',substrate_member:'SMALL'}));valid(r);});
test('AC adapter is never available to ventilation and manual has no electrical fields',()=>{let r=resolve(vent());assert.equal(vals('power_supply_type',r.selection).includes(PW.ADAPTER),false);r=resolve(manualStd());assert.equal(r.fields.some(x=>x.key==='power_supply_type'),false);assert.equal(r.resolvedFields.power_supply_type,'NOT_APPLICABLE');});
test('completed configuration produces shutter BOM components',()=>{const r=resolve(base());valid(r);const types=r.orderConfiguration.components.map(x=>x.componentType);assert.ok(types.includes('reform_shutter_frame'));assert.ok(types.includes('shutter_body'));assert.ok(types.includes('shutter_box'));assert.ok(types.includes('remote_control'));});
