import test from 'node:test';
import assert from 'node:assert/strict';
import { loadRegisteredRuntime } from '../src/catalog/runtime-master/runtime-master-registry.mjs';
import { resolveRuntimeAppProduct, runtimeAppIntegrationInventory } from '../src/catalog/runtime-master/runtime-app-bridge.mjs';
import { NEW_CONSTRUCTION_SASH_UI_STANDARD_ORDER, applyNewConstructionSashUiOrder, formatAndSortStandardSizeChoices } from '../src/catalog/runtime-master/new-construction-sash-runtime-ui-contract.mjs';

const GLOBAL_STAGE_ORDER=['PRODUCT','OPENING','CONFIGURATION','SIZE','FINISH','SCREEN','GLAZING','INSTALLATION_SURVEY','OPTION'];
const stageIndex=new Map(GLOBAL_STAGE_ORDER.map((stage,index)=>[stage,index]));
const technical=new Set(['construction','actual_w','actual_h','runtime_technical_state','dependency_only_selector','provider_id','source_id','legacyConstruction','legacyConfiguration']);
function assertSemanticOrder(result){let prior=-1;for(const field of result.fields){assert.ok(!technical.has(field.key),`technical field leaked: ${field.key}`);const index=stageIndex.get(field.semanticStage);assert.ok(Number.isInteger(index),`semantic stage unmapped at ${field.key}: ${field.semanticStage}`);assert.ok(index>=prior,`semantic stage order regressed at ${field.key}: ${field.semanticStage}`);prior=index;}}
function assertSizeUi(values){assert.ok(values.length>0);for(const row of values)assert.match(row.displayLabel,/^\S+ ｜ W \d+ × H \d+$/u);for(let i=1;i<values.length;i+=1){const a=values[i-1].sizeMetadata,b=values[i].sizeMetadata;assert.ok(a.actualW<b.actualW||(a.actualW===b.actualW&&a.actualH<=b.actualH),`size sort violation: ${a.actualW}x${a.actualH} -> ${b.actualW}x${b.actualH}`);}}
async function reachStandardSize(productId,windowType){const selection={window_type:windowType};for(let pass=0;pass<40;pass+=1){const result=await resolveRuntimeAppProduct(productId,selection);const size=result.fields.find((field)=>field.key==='size');if(size?.values?.length)return result;const missing=result.fields.find((field)=>field.key!=='size'&&field.required&&selection[field.key]===undefined&&field.values?.length);if(!missing)return result;const preferred=missing.key==='size_mode'?missing.values.find((row)=>row.value==='STANDARD'):null;selection[missing.key]=(preferred??missing.values[0]).value;}throw new Error(`STANDARD size frontier did not converge: ${windowType}`);}
function expectedFormalCallCode(row){const id=String(row?.id??'');const five=id.match(/(?:^|[-_])(\d{5})$/);if(five)return five[1];const w=row?.nominal_w===null||row?.nominal_w===undefined?'':String(row.nominal_w).trim();const h=row?.nominal_h===null||row?.nominal_h===undefined?'':String(row.nominal_h).trim();if(w.includes('-')&&h)return `${w}-${h}`;if(w&&h&&(id.endsWith(`-${w}-${h}`)||id===`${w}-${h}`))return `${w}-${h}`;if(typeof row?.nominal_w==='string'&&typeof row?.nominal_h==='string'&&w&&h)return `${w}${h}`;return null;}

test('v1.6 semantic aliases fix field order, common labels and internal-field exposure',()=>{const result=applyNewConstructionSashUiOrder([{key:'glass_base',displayLabel:'glass',displayOrder:1},{key:'construction',displayLabel:'工法',displayOrder:2},{key:'shutter_type',displayLabel:'シャッター種類',displayOrder:3},{key:'window_type',displayLabel:'窓種',displayOrder:99},{key:'screen_type',displayLabel:'screen type',displayOrder:4},{key:'handing',displayLabel:'handing',displayOrder:5},{key:'panel_count',displayLabel:'panel',displayOrder:6},{key:'window_configuration',displayLabel:'構成',displayOrder:6.5},{key:'option',displayLabel:'option',displayOrder:7}]);assert.deepEqual(result.map((row)=>row.key),['window_type','shutter_type','window_configuration','handing','panel_count','screen_type','glass_base','option']);assert.equal(result.find((row)=>row.key==='window_type').displayLabel,'窓種類');assert.equal(result.find((row)=>row.key==='window_configuration').displayLabel,'連窓構成');assert.equal(result.find((row)=>row.key==='handing').displayLabel,'開き勝手（吊元）');assert.equal(result.find((row)=>row.key==='panel_count').displayLabel,'建具・枚数');assert.equal(result.find((row)=>row.key==='screen_type').displayLabel,'網戸形式');assert.equal(result.find((row)=>row.key==='option').displayLabel,'その他オプション');});

test('v1.6 size formatter preserves exact Runtime call codes and rejects lossy numeric reconstruction',()=>{const result=formatAndSortStandardSizeChoices([{value:'c',runtimeValueRow:{metadata:{callCode:'06907',actualW:730,actualH:770}}},{value:'a',runtimeValueRow:{source:{nominal_w:'060',nominal_h:'09',actual_w:640,actual_h:970}}},{value:'b',runtimeValueRow:{metadata:{callCode:'06005',actualW:640,actualH:570}}},{value:'SZ-LIX-TW-UNIT-HIKI-Z-06003',runtimeValueRow:{source:{id:'SZ-LIX-TW-UNIT-HIKI-Z-06003',nominal_w:60,nominal_h:3,actual_w:640,actual_h:370}}},{value:'SZ-LIX-TW-FLAT-Z-251-2-18',runtimeValueRow:{source:{id:'SZ-LIX-TW-FLAT-Z-251-2-18',nominal_w:'251-2',nominal_h:'18',actual_w:2550,actual_h:1830}}},{value:'SZ-LIX-TW-UNIT-HIKI-Z-25118P2',runtimeValueRow:{source:{id:'SZ-LIX-TW-UNIT-HIKI-Z-25118P2',nominal_w:'251-2',nominal_h:18,actual_w:2550,actual_h:1830}}}]);assert.deepEqual(result.map((row)=>row.displayLabel),['06003 ｜ W 640 × H 370','06005 ｜ W 640 × H 570','06009 ｜ W 640 × H 970','06907 ｜ W 730 × H 770','251-2-18 ｜ W 2550 × H 1830','251-2-18 ｜ W 2550 × H 1830']);assert.throws(()=>formatAndSortStandardSizeChoices([{value:'lossy',runtimeValueRow:{source:{nominal_w:60,nominal_h:3,actual_w:640,actual_h:370}}}]),(error)=>error.code==='RUNTIME_SIZE_DISPLAY_DATA_MISSING');assert.throws(()=>formatAndSortStandardSizeChoices([{value:'bad',runtimeValueRow:{metadata:{callCode:'06005',actualW:640}}}]),(error)=>error.code==='RUNTIME_SIZE_DISPLAY_DATA_MISSING');});

test('all currently registered EW/TW window types obey the global semantic stage order',async()=>{for(const[manufacturer,series,productId]of[['LIXIL','EW','SER-LIX-EW'],['LIXIL','TW','SER-LIXIL-TW']]){const runtime=await loadRegisteredRuntime(manufacturer,series);const windows=runtime.master.values.filter((row)=>row.field_name==='window_type'&&row.status==='CURRENT'&&row.runtime_selectable!==false);assert.equal(windows.length,series==='EW'?15:25);for(const window of windows){const result=await resolveRuntimeAppProduct(productId,{window_type:window.canonical_value});assertSemanticOrder(result);assert.equal(result.fields[0]?.key,'window_type');}}});

test('EW/TW standard-size choices use v1.6 display format and deterministic sort',async()=>{const ew=await resolveRuntimeAppProduct('SER-LIX-EW',{window_type:'WT-EW-TATE-SUBERI',window_spec:'SP-EW-TATE-T',handing:'L',size_mode:'STANDARD'});assertSizeUi(ew.fields.find((row)=>row.key==='size').values);const tw=await resolveRuntimeAppProduct('SER-LIXIL-TW',{window_type:'SWT-LIX-TW-UNIT-HIKI',size_mode:'STANDARD',panel_count:'2枚建'});const twSizes=tw.fields.find((row)=>row.key==='size').values;assertSizeUi(twSizes);assert.ok(twSizes.some((row)=>row.displayLabel==='06003 ｜ W 640 × H 370'),'formal TW 06003 must preserve its leading zero');assert.ok(!twSizes.some((row)=>row.displayLabel==='603 ｜ W 640 × H 370'),'lossy TW 603 label must never be shown');});

test('all 25 TW window types preserve formal size codes and expose no duplicate visible labels',async()=>{const runtime=await loadRegisteredRuntime('LIXIL','TW');const windows=runtime.master.values.filter((row)=>row.field_name==='window_type'&&row.status==='CURRENT'&&row.runtime_selectable!==false);const sourceById=new Map((runtime.master.provider?.sizes??[]).map((row)=>[row.id,row]));assert.equal(windows.length,25);for(const window of windows){const result=await reachStandardSize('SER-LIXIL-TW',window.canonical_value);const sizes=result.fields.find((field)=>field.key==='size')?.values??[];assert.ok(sizes.length>0,`${window.canonical_value} must expose STANDARD sizes`);const labels=new Set();for(const size of sizes){const source=sourceById.get(size.value);const formalCode=expectedFormalCallCode(source);assert.ok(formalCode,`${window.canonical_value}/${size.value} must retain enough formal Runtime data for a call code`);assert.equal(size.sizeMetadata?.callCode,formalCode,`${window.canonical_value}/${size.value} must preserve formal call code ${formalCode}`);assert.ok(!labels.has(size.displayLabel),`${window.canonical_value} duplicate visible size label: ${size.displayLabel}`);labels.add(size.displayLabel);}}});

test('formal Product Master re-sync exposes S2H, ThermosL, APW430 and APW431 as READY read-only integrations',async()=>{const inventory=runtimeAppIntegrationInventory();for(const[id,version]of[['SER-LIX-SAMOS2H','v0.9-R4'],['SER-LIX-SAMOSL','v0.7-R2'],['SER-YKK-APW430','20260918-R3'],['SER-YKK-APW431','v1.2']]){const row=inventory.find((item)=>item.id===id);assert.ok(row,`missing integration identity: ${id}`);assert.equal(row.status,'READY');assert.equal(row.selectable,true);assert.equal(row.packageVersion,version);const result=await resolveRuntimeAppProduct(id,{});assert.equal(result.runtimeMaster.sourcePackageIntegrity.match,true);assert.ok(!result.fields.some((field)=>field.key==='construction'));}});
