import test from 'node:test';
import assert from 'node:assert/strict';
import { resolveRuntimeAppProduct } from '../src/catalog/runtime-master/runtime-app-bridge.mjs';

const formalSeries=[['SER-LIX-SAMOS2H',17],['SER-LIX-SAMOSL',17],['SER-YKK-APW430',25],['SER-YKK-APW431',6]];

test('ThermosL formal Runtime v0.7-R2 is exact-integrity materialized from the canonical manifest',async()=>{const result=await resolveRuntimeAppProduct('SER-LIX-SAMOSL',{});assert.equal(result.runtimeMaster.packageVersion,'v0.7-R2');assert.equal(result.runtimeMaster.sourceHash,'4cf2a4b1572f68288fa108ccd33d30cc80d5170f2f5303864ca56ca67c34cec3');assert.equal(result.runtimeMaster.sourcePackageIntegrity?.match,true);assert.equal(result.runtimeMaster.sourcePackageIntegrity?.manifestDriveFileId,'1c-VIgwTqPDTkas0apYqx30AN3PVa71p1');const runtime=result.runtimeMaster.sourcePackageIntegrity.files.find((row)=>row.fileId==='12G_Edo55NWgu38gJjTGcqDZ7HsdpAH2I');assert.ok(runtime);assert.equal(runtime.expected,'e0b84fd83a1a2e3c078db357c67ac7bb751b34860c05a2321e1466c5cad97525');assert.equal(runtime.actual,runtime.expected);assert.equal(runtime.bytes,5147529);assert.equal(runtime.codec,'brotli');});
async function reachStandardSize(productId,windowId){const selection={window_type:windowId};for(let i=0;i<24;i+=1){const result=await resolveRuntimeAppProduct(productId,selection);assert.ok(!result.fields.some((field)=>field.key==='construction'),`${productId}/${windowId}: construction leaked`);const size=result.fields.find((field)=>field.key==='size');if(size?.values?.length)return{result,size};const next=result.fields.find((field)=>field.required&&selection[field.key]===undefined&&field.key!=='size'&&field.dataType!=='NUMBER'&&field.values?.length);if(!next)return{result,size:null};const preferred=next.key==='size_mode'?next.values.find((row)=>row.value==='STANDARD'):null;selection[next.key]=(preferred??next.values[0]).value;}throw new Error(`${productId}/${windowId}: resolver did not stabilize`);}

test('65 newly re-synced formal window types all reach canonical STANDARD size records without construction UI',async()=>{let total=0;for(const[productId,expectedWindows]of formalSeries){const initial=await resolveRuntimeAppProduct(productId,{});const windows=initial.fields.find((field)=>field.key==='window_type')?.values??[];assert.equal(windows.length,expectedWindows,`${productId}: window count`);for(const window of windows){const{size}=await reachStandardSize(productId,window.value);assert.ok(size?.values?.length,`${productId}/${window.value}: no standard size choices`);for(const choice of size.values)assert.match(choice.displayLabel,/^\S+ ｜ W \d+ × H \d+$/u,`${productId}/${window.value}: bad size label`);total+=1;}}assert.equal(total,65);});

test('Samos2H formal Runtime v0.9-R3 is exact-integrity materialized from the canonical manifest',async()=>{const result=await resolveRuntimeAppProduct('SER-LIX-SAMOS2H',{});assert.equal(result.runtimeMaster.packageVersion,'v0.9-R3');assert.equal(result.runtimeMaster.schemaVersion,'2.0');assert.equal(result.runtimeMaster.sourceHash,'cfc55020035df809b83c0f4a25dc0e0b717854344fdb815be8e9a848c2d889c8');assert.equal(result.runtimeMaster.sourcePackageIntegrity?.match,true);assert.equal(result.runtimeMaster.sourcePackageIntegrity?.manifestDriveFileId,'1xnVkGtwoN488zgjoi-FOF9drnaUP-jal');assert.equal(result.runtimeMaster.sourcePackageIntegrity?.files?.length,2);const runtime=result.runtimeMaster.sourcePackageIntegrity.files.find((row)=>row.fileId==='1c-w0-fYEBZubfN6KCy5BfG1Sp41xsKdu');assert.ok(runtime);assert.equal(runtime.expected,'5efa48c3a771d24ef4e7799f725e6dacfac743031d8503c1644d7e8016acdd19');assert.equal(runtime.actual,runtime.expected);assert.equal(runtime.bytes,6375678);assert.equal(runtime.codec,'brotli');const schema=result.runtimeMaster.sourcePackageIntegrity.files.find((row)=>row.fileId==='1LMmXrVfap_xXZXTPoXcos1gWvZqZKtj1');assert.ok(schema);assert.equal(schema.expected,'60594d0caa23db536e627b74c44bae978137bd8d667585e7e9b3091aa1f0cd00');assert.equal(schema.actual,schema.expected);assert.equal(result.fields.find((field)=>field.key==='window_type')?.values?.length,17);});

test('APW430 formal Runtime 20260917-R2 is exact-integrity materialized and exposes 25 windows',async()=>{const result=await resolveRuntimeAppProduct('SER-YKK-APW430',{});assert.equal(result.runtimeMaster.packageVersion,'20260917-R2');assert.equal(result.runtimeMaster.schemaVersion,'product-master-runtime-manifest/1.0');assert.equal(result.runtimeMaster.sourceHash,'1b012a78abfbbb2a6647272f92126d37c3a75d0a52d8b03de4d30e2afe9bcfcc');assert.equal(result.runtimeMaster.sourcePackageIntegrity?.match,true);assert.equal(result.runtimeMaster.sourcePackageIntegrity?.manifestDriveFileId,'1NzsX4C4M2fpOBUvXdXpPLYYfXfF7PNeo');assert.equal(result.runtimeMaster.sourcePackageIntegrity?.files?.length,3);const expected=new Map([['1PP5N_RbSaNjJhuPv1qMUDHjGIaeVgCQo',['c685d3a96d2007c6d78f43893aeaf1bbc139892ad79698e3a97a087fd2690884',61726]],['1AOCQ84DMCxtcBUFluxVo4luwuWNZ8h45',['f731cadc95e72ac9ad75986d49cc630319538e3b2d6c3cec8b4e60a54747ca0f',791465]],['143MG_S6GKaNa7EPUhmFoKoyJdlmJ3i5Q',['f8394c1f047ef0d6e49ee49522ea78f0fd81b32a5d2d1a5536c5bcf63ded6e45',3413266]]]);for(const file of result.runtimeMaster.sourcePackageIntegrity.files){const [sha,bytes]=expected.get(file.fileId);assert.equal(file.expected,sha);assert.equal(file.actual,sha);assert.equal(file.bytes,bytes);}assert.equal(result.fields.find((field)=>field.key==='window_type')?.values?.length,25);});

test('APW431 formal Runtime v1.1 is exact-integrity materialized and exposes all six windows',async()=>{const result=await resolveRuntimeAppProduct('SER-YKK-APW431',{});assert.equal(result.runtimeMaster.packageVersion,'v1.1');assert.equal(result.runtimeMaster.schemaVersion,'product-master-runtime-manifest/2.0');assert.equal(result.runtimeMaster.sourceHash,'7b4331b62d80a356fdd39549c942bb30db8a6e34e9e7d0fd2277c0bccc4f4f27');assert.equal(result.runtimeMaster.sourcePackageIntegrity?.match,true);assert.equal(result.runtimeMaster.sourcePackageIntegrity?.manifestDriveFileId,'1ZcgwXjq0KHiVDG8KCvV6k3NAZM-CDk3J');assert.equal(result.runtimeMaster.sourcePackageIntegrity?.files?.length,3);const expected=new Map([['1dkRyTKPr5PXtnzTGkGvEiTeAGmY4fNXs',['9fff49082f4a0b1026a86baf24fc2cfd112d0d03193124f5f96777b05b694a4a',60431]],['1YhB0n_NZ6Ulolo_-hAiz0in7j1Jwuxun',['386e9abccdc4ba15c1dcfd5bf722cf48f45f4b277e2c6f87182cb215acc8b171',1685250]],['1aPuMxKKl88Q-E64Gixi0_HFpk1YF5_p5',['b14489ab792536b74b0d013020f8a4b9366d5b2b6e501b94f0ac274f8e95bcf9',127228]]]);for(const file of result.runtimeMaster.sourcePackageIntegrity.files){const [sha,bytes]=expected.get(file.fileId);assert.equal(file.expected,sha);assert.equal(file.actual,sha);assert.equal(file.bytes,bytes);}assert.equal(result.fields.find((field)=>field.key==='window_type')?.values?.length,6);assert.ok(!result.fields.some((field)=>['construction','legacyConstruction','legacyConfiguration','internal_construction'].includes(field.key)));});

async function reachGlassType(productId){let result=await resolveRuntimeAppProduct(productId,{});const window=result.fields.find((field)=>field.key==='window_type')?.values?.[0];assert.ok(window);const selection={window_type:window.value};for(let i=0;i<32;i+=1){result=await resolveRuntimeAppProduct(productId,selection);const glass=result.fields.find((field)=>field.key==='glass_type');if(glass?.values?.length)return{result,selection,glass};const next=result.fields.find((field)=>field.required&&selection[field.key]===undefined&&field.dataType!=='NUMBER'&&field.values?.length);if(!next)break;const preferred=next.key==='size_mode'?next.values.find((row)=>row.value==='STANDARD'):null;selection[next.key]=(preferred??next.values[0]).value;}throw new Error(`${productId}: glass_type not reached`);}

test('APW430/APW431 expose semantic glass selectors while fixed and derived glazing stays runtime property metadata',async()=>{for(const productId of ['SER-YKK-APW430','SER-YKK-APW431']){const {result,selection,glass}=await reachGlassType(productId);assert.ok(glass.values.length>=4);assert.ok(result.runtimeProperties?.some((row)=>row.key==='glass_spacer'&&String(row.classification).includes('FIXED')));assert.ok(result.runtimeProperties?.some((row)=>row.key==='gas'&&String(row.classification).includes('FIXED')));assert.ok(result.runtimeProperties?.some((row)=>row.key==='glass_air_layer'&&String(row.classification).includes('DERIVED')));selection.glass_type=glass.values[0].value;const afterType=await resolveRuntimeAppProduct(productId,selection);const detail=afterType.fields.find((field)=>field.key==='glass_detail');assert.ok(detail?.values?.length,productId);selection.glass_detail=detail.values[0].value;const afterDetail=await resolveRuntimeAppProduct(productId,selection);assert.ok(afterDetail.fields.some((field)=>field.key==='glass_function')||productId==='SER-YKK-APW431');assert.ok(!afterDetail.fields.some((field)=>['glass_spacer','gas','glass_air_layer','glass_composition'].includes(field.key)));}});

test('ThermosL custom construction stays hidden and ambiguous internal construction fails closed as review',async()=>{let result;const selection={window_type:'WT-SL-KATTEGUCHI-VENT-FS',size_mode:'CUSTOM',custom_width:700,custom_height:1800};for(let i=0;i<12;i+=1){result=await resolveRuntimeAppProduct('SER-LIX-SAMOSL',selection);const next=result.fields.find((field)=>field.required&&selection[field.key]===undefined&&!['custom_width','custom_height','size'].includes(field.key)&&field.values?.length);if(!next)break;selection[next.key]=next.values[0].value;}result=await resolveRuntimeAppProduct('SER-LIX-SAMOSL',selection);assert.ok(!result.fields.some((field)=>field.key==='construction'));assert.equal(result.dimensionResult?.status,'REVIEW_REQUIRED');assert.equal(result.dimensionResult?.code,'REVIEW_REQUIRED_CONSTRUCTION_AMBIGUOUS');assert.equal(result.orderReady,false);});
