import test from 'node:test';
import assert from 'node:assert/strict';
import { resolveRuntimeAppProduct } from '../src/catalog/runtime-master/runtime-app-bridge.mjs';

const formalSeries=[['SER-LIX-SAMOS2H',17],['SER-LIX-SAMOSL',17],['SER-YKK-APW430',25],['SER-YKK-APW431',6]];
async function reachStandardSize(productId,windowId){const selection={window_type:windowId};for(let i=0;i<24;i+=1){const result=await resolveRuntimeAppProduct(productId,selection);assert.ok(!result.fields.some((field)=>field.key==='construction'),`${productId}/${windowId}: construction leaked`);const size=result.fields.find((field)=>field.key==='size');if(size?.values?.length)return{result,size};const next=result.fields.find((field)=>field.required&&selection[field.key]===undefined&&field.key!=='size'&&field.dataType!=='NUMBER'&&field.values?.length);if(!next)return{result,size:null};const preferred=next.key==='size_mode'?next.values.find((row)=>row.value==='STANDARD'):null;selection[next.key]=(preferred??next.values[0]).value;}throw new Error(`${productId}/${windowId}: resolver did not stabilize`);}

test('65 newly re-synced formal window types all reach canonical STANDARD size records without construction UI',async()=>{let total=0;for(const[productId,expectedWindows]of formalSeries){const initial=await resolveRuntimeAppProduct(productId,{});const windows=initial.fields.find((field)=>field.key==='window_type')?.values??[];assert.equal(windows.length,expectedWindows,`${productId}: window count`);for(const window of windows){const{size}=await reachStandardSize(productId,window.value);assert.ok(size?.values?.length,`${productId}/${window.value}: no standard size choices`);for(const choice of size.values)assert.match(choice.displayLabel,/^\S+ ｜ W \d+ × H \d+$/u,`${productId}/${window.value}: bad size label`);total+=1;}}assert.equal(total,65);});

test('APW431 formal Runtime package is READY, integrity-checked and exposes all six windows',async()=>{const result=await resolveRuntimeAppProduct('SER-YKK-APW431',{});assert.equal(result.runtimeMaster.packageVersion,'v1.0');assert.equal(result.runtimeMaster.schemaVersion,'product-master-runtime-manifest/1.0');assert.equal(result.runtimeMaster.sourceHash,'f83998aa540ff39907627089adbe84eae32ba9850b36fa8ad7f40a30e2502511');assert.equal(result.runtimeMaster.sourcePackageIntegrity?.match,true);assert.equal(result.runtimeMaster.sourcePackageIntegrity?.manifestDriveFileId,'1Rfrbcdu5j9ZsWGX9PDyC82iEKWUHhCyv');assert.equal(result.runtimeMaster.sourcePackageIntegrity?.files?.length,3);assert.equal(result.fields.find((field)=>field.key==='window_type')?.values?.length,6);assert.ok(!result.fields.some((field)=>['construction','legacyConstruction','legacyConfiguration','internal_construction'].includes(field.key)));});

test('ThermosL custom construction stays hidden and ambiguous internal construction fails closed as review',async()=>{let result;const selection={window_type:'WT-SL-KATTEGUCHI-VENT-FS',size_mode:'CUSTOM',custom_width:700,custom_height:1800};for(let i=0;i<12;i+=1){result=await resolveRuntimeAppProduct('SER-LIX-SAMOSL',selection);const next=result.fields.find((field)=>field.required&&selection[field.key]===undefined&&!['custom_width','custom_height','size'].includes(field.key)&&field.values?.length);if(!next)break;selection[next.key]=next.values[0].value;}result=await resolveRuntimeAppProduct('SER-LIX-SAMOSL',selection);assert.ok(!result.fields.some((field)=>field.key==='construction'));assert.equal(result.dimensionResult?.status,'REVIEW_REQUIRED');assert.equal(result.dimensionResult?.code,'REVIEW_REQUIRED_CONSTRUCTION_AMBIGUOUS');assert.equal(result.orderReady,false);});
