import json
from pathlib import Path
root=Path(__file__).resolve().parents[2]/'contracts/window-seven'
packet=json.loads((root/'promotion-review-packet.json').read_text())
summary=json.loads((root/'summary.json').read_text())
labels={f['field_id']:{'product':f['manufacturer']+' '+f['product'],'label':' / '.join(f['ui_label'])} for f in json.loads((root/'field-inventory.json').read_text())['fields']}
data={'packet':packet,'labels':labels}
html='''<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>独立Promotion Approval</title><style>body{font:16px system-ui;background:#f3f6f7;color:#18303c;margin:0}main{max-width:1180px;margin:auto;padding:32px}.card{background:white;border:1px solid #d4e0e5;border-radius:12px;padding:24px;margin:18px 0}p{line-height:1.7}input{font:inherit;padding:10px;width:60%}summary{cursor:pointer;padding:14px 0}details{border-bottom:1px solid #dde4e7}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px;background:#f4f7f8;padding:14px}code{overflow-wrap:anywhere}a{color:#176b62}</style><main><h1>217 Fieldの独立Promotion Approval</h1><div class="card"><p>Evidence Acceptanceは本人承認により651件Accepted、Missing Claims=0です。今回は、以下の固定Dossier・対象Contract・採用EvidenceのHashに基づく、217件のPROVISIONAL → FORMAL昇格Approvalが対象です。既存Evidence Acceptanceの再承認ではありません。</p><p>Runtime・Product Master・UI・保存形式・出力・既存Canonical Mappingの変更は0です。対象ContractはstatusだけをFORMALへ変更します。</p><p>Promotion Packet Content SHA256<br><code id="hash"></code></p><a href="promotion-review-packet.json">全DossierとApproval対象</a> · <a href="evidence-acceptance.json">Accepted Evidence</a> · <a href="evidence/human-acceptance-decisions.json">本人Acceptance記録</a></div><div class="card"><label>商品・Field検索 <input id="q" placeholder="TW、ウチリモ、glass、frameなど"></label><p id="count"></p><div id="list"></div></div><p>この画面は承認を送信しません。本人の独立Approval後、固定Payloadを正式記録し、中央Validator・Exact-HEAD CI・Merge・Merge後検証を続行します。</p></main><script type="application/json" id="data">__DATA__</script><script>const d=JSON.parse(document.querySelector('#data').textContent);document.querySelector('#hash').textContent=d.packet.packet_content_sha256;function render(){const q=document.querySelector('#q').value.toLowerCase(),rows=d.packet.fields.filter(f=>JSON.stringify([f.field_id,d.labels[f.field_id]]).toLowerCase().includes(q)),list=document.querySelector('#list');list.replaceChildren();document.querySelector('#count').textContent=`${rows.length} Field`;for(const f of rows){const box=document.createElement('details'),title=document.createElement('summary'),l=d.labels[f.field_id];title.textContent=`${l.product} | ${l.label} | ${f.field_id.split(':').at(-1)} | PROVISIONAL → FORMAL`;box.append(title);const pre=document.createElement('pre');pre.textContent=JSON.stringify({dossier:f.dossier,proposed_approval_payload:f.proposed_approval_payload,target_contract:f.target_contract},null,2);box.append(pre);list.append(box)}}document.querySelector('#q').oninput=render;render();</script></html>'''
(root/'promotion-review.html').write_text(html.replace('__DATA__',json.dumps(data,ensure_ascii=False).replace('</','<\\/')))
# Preserve the original acceptance screen as history, clearly separate current state.
p=root/'review.html';original=p.read_text()
if 'EVIDENCE_ACCEPTANCE_RECORDED' not in original:
    original=original.replace('<main>','<main><!-- EVIDENCE_ACCEPTANCE_RECORDED --><div class="card"><p>この固定Evidence Packetは本人承認により651件Acceptedとして記録済みです。以下は承認時点の履歴です。</p><a href="promotion-review.html">独立Promotion Approval画面を開く</a></div>',1);p.write_text(original)
(root/'REPORT.txt').write_text('WINDOW 7 PRODUCT SELECTION CONTRACT FORMALIZATION = PENDING_INDEPENDENT_PROMOTION_APPROVAL\n\n'+json.dumps(summary,ensure_ascii=False,indent=2)+'\n\nEvidence Acceptance: direct human approval recorded; accepted 651; rejected 0; Missing Claims 0.\nPromotion: 217 content-bound dossiers prepared; independent approval not yet recorded; all Fields remain PROVISIONAL.\nRuntime Diff 0; existing browser/source QA carry-forward applies to unchanged Runtime bytes.\nSee promotion-review.html and promotion-review-packet.json.\n')
