"""One bounded shared byte guard; no Work or publication executor."""
import pathlib,json,hashlib,subprocess,io,tarfile
BASE='aec4f297c004e10df24f2d7e239ace374e8a3063'
ALLOWED={'scripts/production/release-batch.py', 'contracts/production/shared-release-authority.v1.bundle', 'scripts/production/validate-order4-release.py', 'contracts/production/authority-successors/order5-batch3-predecessor-profile.v1.json', 'scripts/production/order5-batch3-scope.py', 'contracts/production/release-profiles/order5-batch3-thermosl.v1.json', 'contracts/production/order5-batch3-assets/apw431.json', '.github/workflows/common-release-contract.yml', 'contracts/production/current-authority-successor.json', 'contracts/production/shared-release-authority.v1.json', 'scripts/production/validate-order5-release.py', 'src/catalog/runtime-master-packages/ykkap-apw431-v1.2/runtime_manifest.json', 'contracts/production/authority-successors/order5-batch3.v1.json', 'scripts/production/release-contract.py', 'contracts/production/release-profiles/order5-batch3-apw431.v1.json', 'contracts/production/authority-successors/order5-batch3-predecessor-selection.v1.json', 'contracts/production/release-profile.v1.json', 'contracts/production/order5-batch3-scope.v1.json', 'contracts/production/release-profiles/order5-batch3-tw.v1.json', 'contracts/production/order5-batch3-assets/thermosl.json', 'contracts/production/release-profiles/order5-batch3-apw430.v1.json', 'contracts/production/release-profiles.v1.json', 'contracts/production/order5-batch3-assets/tw.json', 'contracts/production/order5-batch3-assets/apw430.json', 'scripts/production/test_order5_batch3_scope.py', 'docs/ORDER5_BATCH3.md'}
IDENTITIES=[('SER-LIX-SAMOSL', 'THERMOSL_UNCHANGED_FORMAL_SELECTION_SAVE_OUTPUT_ORDER5_BATCH3_V1', 'contracts/production/release-profiles/order5-batch3-thermosl.v1.json'), ('SER-LIXIL-TW', 'TW_UNCHANGED_FORMAL_SELECTION_SAVE_OUTPUT_ORDER5_BATCH3_V1', 'contracts/production/release-profiles/order5-batch3-tw.v1.json'), ('SER-YKK-APW430', 'APW430_UNCHANGED_FORMAL_SELECTION_SAVE_OUTPUT_ORDER5_BATCH3_V1', 'contracts/production/release-profiles/order5-batch3-apw430.v1.json'), ('SER-YKK-APW431', 'APW431_UNCHANGED_FORMAL_SELECTION_SAVE_OUTPUT_ORDER5_BATCH3_V1', 'contracts/production/release-profiles/order5-batch3-apw431.v1.json')]
EXCLUDED={'contracts/production/release-profiles/order5-batch3-apw431.v1.json', 'contracts/production/release-profile.v1.json', 'contracts/production/order5-batch3-scope.v1.json', 'contracts/production/release-profiles/order5-batch3-tw.v1.json', 'contracts/production/release-profiles/order5-batch3-thermosl.v1.json', 'contracts/production/release-profiles/order5-batch3-apw430.v1.json', 'contracts/production/current-authority-successor.json', 'contracts/production/authority-successors/order5-batch3.v1.json'}
def digest(b):return hashlib.sha256(b).hexdigest()
def validate(root):
 root=pathlib.Path(root);errors=[];protected={}
 try:
  with tarfile.open(fileobj=io.BytesIO(subprocess.check_output(['git','archive',BASE],cwd=root))) as a:before={m.name:a.extractfile(m).read() for m in a if m.isfile()}
  s=json.loads((root/'contracts/production/order5-batch3-scope.v1.json').read_bytes());assert s['schema']=='ORDER5_BATCHED_NATIVE_SCOPE_V1' and s['starting_main']==BASE and s['product_fact_mutation_allowed'] is False and set(s['allowed_paths'])==ALLOWED,'BATCH3_SCOPE_IDENTITY'
  protected={p:digest(b) for p,b in before.items() if p not in ALLOWED};assert protected==s['protected_sha256'],'INCOMPLETE_NATIVE_PROTECTION'
  for p,h in protected.items():assert (root/p).is_file() and not (root/p).is_symlink() and digest((root/p).read_bytes())==h,'PROTECTED_DRIFT:'+p
  changed=set(subprocess.check_output(['git','diff','--name-only',BASE],cwd=root,text=True).splitlines())|set(subprocess.check_output(['git','ls-files','--others','--exclude-standard'],cwd=root,text=True).splitlines());assert changed<=ALLOWED,'UNAUTHORIZED_NATIVE_PATH'
  assert set(s['candidate_files_sha256'])==ALLOWED-EXCLUDED,'CANDIDATE_PIN_SET'
  for p,h in s['candidate_files_sha256'].items():assert (root/p).is_file() and not (root/p).is_symlink() and digest((root/p).read_bytes())==h,'CANDIDATE_BYTES_DRIFT:'+p
  prior='contracts/production/authority-successors/order5-batch3-predecessor-profile.v1.json';assert (root/prior).read_bytes()==before['contracts/production/release-profile.v1.json'],'PREDECESSOR_PROFILE_DRIFT'
  old=json.loads(before['contracts/production/release-profile.v1.json']);reg=json.loads((root/'contracts/production/release-profiles.v1.json').read_bytes());assert [(x['product_id'],x['scope'],x['path']) for x in reg['profiles']]==IDENTITIES,'BATCH3_PRODUCT_SCOPE_DRIFT'
  for entry in reg['profiles']:
   p=json.loads((root/entry['path']).read_bytes());assert p['scope_admission']['product_id']==entry['product_id'] and p['scope_admission']['scope']==entry['scope'],'PRODUCT_SCOPE_MISMATCH'
   for k in ['repository','destination','approval_roles','mandatory_approvals','gate_approval_roles','minimum_qa','required_ci','terminal_policy']:assert p[k]==old[k],'RELEASE_GUARANTEE_CHANGED:'+k
   assert p['publication_policy']['protected_files']==protected and p['publication_policy']['auto_assign_custom_domains'] is False and not p['publication_policy']['allowed_merge_differences'],'PUBLICATION_PROTECTION_CHANGED'
   qa=p['publication_policy']['native_qa_bindings']['batch3_product'];claims={tuple(v['pointer']):v['value'] for v in qa['claims']};assert claims[('schema',)]=='ORDER5_BATCH3_EXECUTED_PRODUCT_QA_V1' and claims[('status',)]=='PASS' and claims[('errors',)]==[] and claims[('product_id',)]==entry['product_id'] and claims[('scope',)]==entry['scope'] and claims[('viewports',)]==[1280,768,390] and claims[('runtime_errors',)]==0,'PRODUCT_QA_POLICY_CHANGED'
   assert qa['minimums']==[{'pointer':['case_count'],'value':3}] and qa['results_pointer']==['results'] and qa['result_state_key']=='status' and qa['sha_pointer']==['observed_commit'] and qa['url_pointer']==['url'],'PRODUCT_QA_POLICY_CHANGED'
   assert set(p['native_files'])==set(p['native_paths']),'NATIVE_DEPENDENCY_COVERAGE'
   for f,h in p['native_files'].items():assert digest((root/f).read_bytes())==h,'NATIVE_BYTES_DRIFT:'+f
  assert (root/'contracts/production/release-profile.v1.json').read_bytes()==(root/reg['profiles'][0]['path']).read_bytes(),'DEFAULT_PROFILE_DRIFT'
 except (AssertionError,OSError,KeyError,ValueError,subprocess.CalledProcessError) as e:errors.append(str(e))
 return {'status':'FAIL_CLOSED' if errors else 'PASS','errors':errors,'authorized_paths':sorted(ALLOWED) if not errors else [],'verified_unchanged_sha256':protected if not errors else {},'protected_files':len(protected),'product_fact_mutations':0,'completed_work':'INSPECT_ONLY','deployment':'NOT_EXECUTED'}
if __name__=='__main__':
 import sys
 r=validate(pathlib.Path(__file__).resolve().parents[2]);print(json.dumps({k:v for k,v in r.items() if k not in ['authorized_paths','verified_unchanged_sha256']}));sys.exit(0 if r['status']=='PASS' else 2)
