import { brotliDecompressSync } from 'node:zlib';
import p1 from './samos2h-data/part-01.mjs';
import p2 from './samos2h-data/part-02.mjs';
import p3 from './samos2h-data/part-03.mjs';
import p4 from './samos2h-data/part-04.mjs';
import p5 from './samos2h-data/part-05.mjs';
import p6 from './samos2h-data/part-06.mjs';
import p7 from './samos2h-data/part-07.mjs';
import p8 from './samos2h-data/part-08.mjs';
import p9 from './samos2h-data/part-09.mjs';
import p10 from './samos2h-data/part-10.mjs';
import p11 from './samos2h-data/part-11.mjs';
import p12 from './samos2h-data/part-12.mjs';
import p13 from './samos2h-data/part-13.mjs';
import p14 from './samos2h-data/part-14.mjs';
import p15 from './samos2h-data/part-15.mjs';
import p16 from './samos2h-data/part-16.mjs';
import p17 from './samos2h-data/part-17.mjs';
import p18 from './samos2h-data/part-18.mjs';
import p19 from './samos2h-data/part-19.mjs';
import p20 from './samos2h-data/part-20.mjs';
const payload=p1+p2+p3+p4+p5+p6+p7+p8+p9+p10+p11+p12+p13+p14+p15+p16+p17+p18+p19+p20;
export const SAMOS2H_SOURCE=JSON.parse(brotliDecompressSync(Buffer.from(payload,'base64')).toString('utf8'));
console.log('S2H_TABLE_SHAPES',JSON.stringify({source:SAMOS2H_SOURCE.source,counts:SAMOS2H_SOURCE.counts,color:SAMOS2H_SOURCE.colors?.[0],glass:SAMOS2H_SOURCE.glasses?.[0],screen:SAMOS2H_SOURCE.screens?.[0],net:SAMOS2H_SOURCE.nets?.[0],screenLimit:SAMOS2H_SOURCE.screenLimits?.[0],option:SAMOS2H_SOURCE.options?.[0],optionRule:SAMOS2H_SOURCE.optionRules?.[0],golden:SAMOS2H_SOURCE.golden?.[0],appControl:SAMOS2H_SOURCE.appControl?.[0]}));
